apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec:
  compositeTypeRef:
    apiVersion: ''
    kind: ''
  resources:
    # Argocd ApplicationSet Resource
    - name: 'Argocd ApplicationSet'
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: ''
          toFieldPath: ''
        - type: FromCompositeFieldPath
          fromFieldPath: ''
          toFieldPath: ''
      base:
        apiVersion: ''
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: ApplicationSet
              metadata:
                name: $(params.prbranchname)-basic-argo-appset
                namespace: argocd
              spec:
                goTemplate: true
                goTemplateOptions: ['missingkey=error']
                generators:
                  - git:
                      repoURL: https://github.com/TluwaniMS/argocd-app-of-app-test.git
                      revision: master
                      files:
                        - path: 'basi-app-set-dev-test-with-git-file-generator/*.json'
                templatePatch: |
                  spec:
                    source:
                      # Dev conditional config set-up.
                      {{- if eq .name "dev" }}
                      helm:
                        parameters:
                          - name: envPrefix
                            value: {{.helmParameters.envPrefix | toJson}}
                          - name: deployment.replicas
                            value: {{.helmParameters.deployment.replicas | toJson }}
                          - name: container.image
                            value: {{.helmParameters.container.image | toJson }}
                          - name: container.tag
                            value: {{.helmParameters.container.tag | toJson }}
                      {{- end }}
                      # Staging conditional config set-up.
                      {{- if eq .name "staging" }}
                      helm:
                        values: |
                          envPrefix: {{.helmParameters.envPrefix | toJson}}
                          deployment:
                            replicas: {{.helmParameters.deployment.replicas | toJson }}
                          container:
                            image: {{.helmParameters.container.image | toJson }}
                            tag: {{.helmParameters.container.tag | toJson }}
                      {{- end }}
                      # Prod conditional config set-up.
                      {{- if eq .name "prod" }}
                      helm:
                        valueFiles:
                          - {{.valueFiles | toJson }}
                      {{- end }}
                template:
                  metadata:
                    name: '{{.name}}-app'
                  spec:
                    project: default
                    source:
                      repoURL: https://github.com/TluwaniMS/basic-node-js-web-server-deployment
                      targetRevision: master
                      path: '{{.loc}}'
                    destination:
                      server: '{{.server}}'
                      namespace: '$(params.prbranchname)-apps'
                    syncPolicy:
                      automated:
                        prune: true
                        selfHeal: true
                      syncOptions:
                        - CreateNamespace=true
    # Test Resource
    - name: 'Test'
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: ''
          toFieldPath: ''
      base:
        apiVersion: ''
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: tests.testkube.io/v3
              kind: Test
              metadata:
                name: $(params.prbranchname)-basic-node-web-page-playwright-testing
                namespace: testkube
                labels:
                  test-type: playwright-e2e-test
              spec:
                type: playwright/test
                content:
                  type: git
                  repository:
                    type: git
                    uri: https://github.com/TluwaniMS/basic-playwright-learning
                  branch: master
                executionRequest:
                  variables:
                    BASE_URL:
                      name: BASE_URL
                      # To be updated to be dynamic.
                      value: http://localhost:3002
                      type: basic
                    USER_NAME:
                      name: USER_NAME
                      value: 'Jack'
                      type: basic
                    ENVIRONMENT:
                      name: ENVIRONMENT
                      value: 'development'
                      type: basic
    # Test Trigger Resource
    - name: 'Test-Trigger'
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: ''
          toFieldPath: ''
        - type: FromCompositeFieldPath
          fromFieldPath: ''
          toFieldPath: ''
        - type: FromCompositeFieldPath
          fromFieldPath: ''
          toFieldPath: ''
      base:
        apiVersion: ''
        kind: Object
        spec:
          forProvider:
            manifest:
              apiVersion: tests.testkube.io/v1
              kind: TestTrigger
              metadata:
                name: $(params.prbranchname)-pr-testtrigger-example
                namespace: testkube
              spec:
                resource: deployment
                resourceSelector:
                  namespace: $(params.prbranchname)-apps
                  name: parameters-dev-basic-node-web-server-deployment
                event: created
                action: run
                execution: test
                testSelector:
                  name: $(params.prbranchname)-basic-node-web-page-playwright-testing
                  namespace: testkube
