apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsandboxgenerators
spec:
  compositeTypeRef:
    apiVersion: 'tlou.kgolo/v1alpha1'
    kind: 'XSandBoxGenerator'
  resources:
    - name: Service
      patches:
        - fromFieldPath: 'metadata.namespace' # Ensure namespace is patched here
          toFieldPath: 'spec.forProvider.manifest.metadata.namespace'
      base:
        apiVersion: 'kubernetes.crossplane.io/v1alpha1'
        kind: Object
        metadata:
          name: 'service'
        spec:
          forProvider:
            manifest:
              apiVersion: v1
              kind: Service
              metadata:
                name: basic-node-web-server-service
                namespace: default
              spec:
                type: ClusterIP
                selector:
                  app: basic-node-web-server
                ports:
                  - protocol: TCP
                    port: 3002
                    targetPort: 3002
    # Argocd ApplicationSet Resource
    - name: Deployment
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: 'spec.name'
            strategy: string
            string:
              fmt: '%s-deployment'
          toFieldPath: 'spec.forProvider.manifest.metadata.name'
        - fromFieldPath: 'metadata.namespace' # Ensure namespace is patched here
          toFieldPath: 'spec.forProvider.manifest.metadata.namespace'
      base:
        apiVersion: 'kubernetes.crossplane.io/v1alpha1'
        kind: Object
        metadata:
          name: 'deployment'
          namespace: default
        spec:
          forProvider:
            manifest:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: basic-node-web-server-deployment
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: basic-node-web-server
                template:
                  metadata:
                    labels:
                      app: basic-node-web-server
                  spec:
                    containers:
                      - name: basic-node-web-server
                        image: tm63/basic-node-web-server:v1.3.0
                        imagePullPolicy: IfNotPresent
                        ports:
                          - containerPort: 3002
