apiVersion: apiextensions.crossplane.io/v1
kind: Composition
spec:
  compositeTypeRef:
    apiVersion: ''
    kind: ''
  resources:
    # Argocd ApplicationSet Resource
    - name: 
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: ''
          toFieldPath: ''
        - type: FromCompositeFieldPath
          fromFieldPath: ''
          toFieldPath: ''
        - type: FromCompositeFieldPath
          fromFieldPath: ''
          toFieldPath: ''
      base:
        apiVersion: ''
        kind: Object
        metadata:
          name: ''
        spec:
          forProvider:
            manifest:
