apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-service-access
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['get', 'list', 'watch', 'create', 'update', 'patch', 'delete']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-service-access-binding
subjects:
  - kind: ServiceAccount
    name: crossplane-contrib-provider-kubernetes-a3cbbe355fa7
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: crossplane-service-access
  apiGroup: rbac.authorization.k8s.io
