apiVersion: tlou.kgolo/v1alpha1
kind: XSandBoxGitFileGenerator
metadata:
  name: mars-application
spec:
  testKube:
    test:
      type: playwright/test
      repository:
        type: git
        uri: https://github.com/TluwaniMS/basic-playwright-learning
        branch: master
    testTrigger:
      resourceSelector:
        resourceType: deployment
  appset:
    generator:
      repoUrl: https://github.com/TluwaniMS/argocd-app-of-app-test.git
      revision: master
      filePaths:
        - 'basi-app-set-dev-test-with-git-file-generator/*.json'
    source:
      repoUrl: https://github.com/TluwaniMS/basic-node-js-web-server-deployment
      targetRevision: master
