apiVersion: tlou.kgolo/v1alpha1
kind: XSandBoxGitFileGenerator
metadata:
  name: mars-application
spec:
  pullRequest: feature/mars-01
  testKube:
    test:
      type: playwright/test
      repository:
        type: git
        uri: https://github.com/TluwaniMS/basic-playwright-learning
        branch: master
    testTrigger:
      resourceSelector:
        resourceType: deployment
  appset:
    project: default
    generator:
      repoUrl: https://github.com/TluwaniMS/argo-app-deployments
      revision: master
      filePaths:
        - path: 'dev-app/*.json'
    source:
      repoUrl: https://github.com/TluwaniMS/basic-node-js-web-server-deployment
      targetRevision: master
