apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsandboxgitfilegenerators
spec:
  compositeTypeRef:
    apiVersion: 'tlou.kgolo/v1alpha1'
    kind: 'XSandBoxGitFileGenerator'
  resources:
    - name: 'ArgocdAppset'
      patches:
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: 'metadata.name'
              - fromFieldPath: 'spec.pullRequest'
            strategy: string
            string:
              fmt: '%s-%s-argo-appset'
          toFieldPath: 'spec.forProvider.manifest.metadata.name'
        - type: FromCompositeFieldPath
          fromFieldPath: 'spec.appset.generator.repoUrl'
          toFieldPath: 'spec.forProvider.manifest.spec.generators[0].repoURL'
        - type: FromCompositeFieldPath
          fromFieldPath: 'spec.appset.generator.revision'
          toFieldPath: 'spec.forProvider.manifest.spec.generators[0].revision'
        - type: FromCompositeFieldPath
          fromFieldPath: 'spec.appset.generator.filePath'
          toFieldPath: 'spec.forProvider.manifest.spec.generators[0].files'
        - type: FromCompositeFieldPath
          fromFieldPath: 'spec.appset.source.repoUrl'
          toFieldPath: 'spec.forProvider.manifest.spec.template.spec.source.repoURL'
        - type: FromCompositeFieldPath
          fromFieldPath: 'spec.appset.source.targetRevision'
          toFieldPath: 'spec.forProvider.manifest.spec.template.spec.source.targetRevision'
        - type: FromCompositeFieldPath
          fromFieldPath: 'spec.appset.source.targetRevision'
          toFieldPath: 'spec.forProvider.manifest.spec.template.spec.project'
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: 'metadata.name'
              - fromFieldPath: 'spec.pullRequest'
            strategy: string
            string:
              fmt: '%s-%s-apps'
          toFieldPath: 'spec.forProvider.manifest.spec.template.spec.destination.namespace'
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: 'metadata.name'
              - fromFieldPath: 'spec.pullRequest'
            strategy: string
            string:
              fmt: '%s-%s-argo'
          toFieldPath: 'spec.forProvider.manifest.spec.template.metadata.name'
      base:
        apiVersion: 'kubernetes.crossplane.io/v1alpha1'
        kind: Object
        metadata:
          name: 'argocd-appset'
        spec:
          providerConfigRef:
            name: kubernetes-provider-config
          forProvider:
            manifest:
              apiVersion: argoproj.io/v1alpha1
              kind: ApplicationSet
              metadata:
                name: basic-argo-appset
                namespace: argocd
              spec:
                goTemplate: true
                goTemplateOptions: ['missingkey=error']
                generators:
                  - git:
                      repoURL: ""
                      revision: ""
                      files: []
                template:
                  metadata:
                    name: 'app'
                  spec:
                    project: default
                    source:
                      repoURL: https://github.com/TluwaniMS/basic-node-js-web-server-deployment
                      targetRevision: master
                      path: '{{.loc}}'
                    destination:
                      server: '{{.server}}'
                      namespace: ''
                    syncPolicy:
                      automated:
                        prune: true
                        selfHeal: true
                      syncOptions:
                        - CreateNamespace=true

    - name: 'TestKubeTest'
      patches: FromCompositeFieldPath
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: 'metadata.name'
              - fromFieldPath: 'spec.pullRequest'
            strategy: string
            string:
              fmt: '%s-%s-test'
          toFieldPath: 'spec.forProvider.manifest.metadata.name'
        - type: FromCompositeFieldPath
          fromFieldPath: 'spec.testKube.test.type'
          toFieldPath: 'spec.forProvider.manifest.spec.type'
        - type: FromCompositeFieldPath
          fromFieldPath: 'spec.testKube.test.repository'
          toFieldPath: 'spec.forProvider.manifest.spec.content.repository'
      base:
        apiVersion: 'kubernetes.crossplane.io/v1alpha1'
        kind: Object
        metadata:
          name: 'testkube-test'
        spec:
          providerConfigRef:
            name: kubernetes-provider-config
          forProvider:
            manifest:
              apiVersion: tests.testkube.io/v3
              kind: Test
              metadata:
                name: playwright-testing
                namespace: testkube
              spec:
                type: playwright/test
                content:
                  type: git
                  repository:
                    type: git
                    uri: https://github.com/TluwaniMS/basic-playwright-learning
                    branch: master
                executionRequest:
                  variables:
                    USER_NAME:
                      name: USER_NAME
                      value: 'Jack'
                      type: basic
                    ENVIRONMENT:
                      name: ENVIRONMENT
                      value: 'development'
                      type: basic
                    BASE_URL:
                      name: BASE_URL
                      value: ''
                      type: basic
    - name: 'TestKubeTestTrigger'
      patches: FromCompositeFieldPath
        - type:
          toFieldPath: 'spec.forProvider.manifest'
      base:
        apiVersion: 'kubernetes.crossplane.io/v1alpha1'
        kind: Object
        metadata:
          name: 'testkube-test-trigger'
        spec:
          providerConfigRef:
            name: kubernetes-provider-config
          forProvider:
            manifest:
