apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xsandboxgitfilegenerators
spec:
  compositeTypeRef:
    apiVersion: 'tlou.kgolo/v1alpha1'
    kind: 'XSandBoxGitFileGenerator'
  resources:
    - name: 'ArgocdAppset'
      patches:
        - type:
          toFieldPath: ''
      base:
        apiVersion: 'kubernetes.crossplane.io/v1alpha1'
        kind: Object
        metadata:
          name: 'argocd-appset'
        spec:
          providerConfigRef:
            name: kubernetes-provider-config
          forProvider:
            manifest:
    - name: 'TestKubeTest'
      patches:
        - type:
          toFieldPath: ''
      base:
        apiVersion: 'kubernetes.crossplane.io/v1alpha1'
        kind: Object
        metadata:
          name: 'testkube-test'
        spec:
          providerConfigRef:
            name: kubernetes-provider-config
          forProvider:
            manifest:
    - name: 'TestKubeTestTrigger'
      patches:
        - type:
          toFieldPath: ''
      base:
        apiVersion: 'kubernetes.crossplane.io/v1alpha1'
        kind: Object
        metadata:
          name: 'testkube-test-trigger'
        spec:
          providerConfigRef:
            name: kubernetes-provider-config
          forProvider:
            manifest:
