apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsandboxgitfilegenerators.tlou.kgolo
spec:
  group: tlou.kgolo
  names:
    kind: XSandBoxGitFileGenerator
    plural: xsandboxgitfilegenerators
  claimNames:
    kind: SandBoxGitFileGenerator
    plural: sandboxgitfilegenerators
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                testkube:
                  type: object
                  properties:
                    test:
                      type: object
                      properties:
                        type:
                          type: string
                        repository:
                          type: object
                          properties:
                            type:
                              type: string
                            uri:
                              type: string
                            branch:
                              type: string
                    testTrigger:
                      type: object
                      properties:
                        resourceSelector:
                          type: object
                          properties:
                            resourceType:
                              type: string
                appset:
                  type: object
                  properties:
                    generator:
                      type: object
                      properties:
                        repoUrl:
                          type: string
                        revision:
                          type: string
                        filePath:
                          type: array
                          items:
                            type: string
                    source:
                      type: object
                      properties:
                        repoUrl:
                          type: string
                        targetRevision:
                          type: string
